### PR TITLE
task7

### PR DESCRIPTION
**Pull request by ihargit**
- [x] 1 - authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.yaml file
- [x] 3 - import-service serverless.yaml file has authorizer configuration for the importProductsFile lambda. Request to the importProductsFile lambda should work only with correct authorization_token being decoded and checked by basicAuthorizer lambda. Response should be in 403 HTTP status if access is denied for this user (invalid authorization_token) and in 401 HTTP status if Authorization header is not provided.
- [x] 5 - update client application to send Authorization: Basic authorization_token header on import. Client should get authorization_token value from browser localStorage https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage authorization_token = localStorage.getItem('authorization_token')

https://dm9otfstrcg58.cloudfront.net/admin/products - csv import page
**localstorage**:
key: authorization_token
value: aWhhcmdpdDpURVNUX1BBU1NXT1JE

`localStorage.setItem('authorization_token', 'aWhhcmdpdDpURVNUX1BBU1NXT1JE');`

GET https://vbe3615vrf.execute-api.eu-west-1.amazonaws.com/dev/import - to check 401 error

### CODE REVIEW

**Comment by Max-Korsakov** [comment]
seems it doesn't allow to upload file even auth token was set to localstorage

image

**Comment by ihargit** [comment]
> seems it doesn't allow to upload file even auth token was set to localstorage
> 
> image



image
image
image
image
Hello, just checked twice, successful. Possible you need to clean cash / check token and try again. Or please, contact me and we might check it on my machine.

**Comment by Max-Korsakov** [comment]
Tried again. The same result. It seems there is no auth header
image

**Comment by ihargit** [comment]
> Tried again. The same result. It seems there is no auth header
Tryed from Edge, first time - successfully.
image
About auth header - if you do not provide auth_token from local storage, this header won't be added.

**Comment by ihargit** [comment]
Possible, we need to have online session on Skype to check if we do the same things.

**Comment by Max-Korsakov** [comment]
Contact me today please
https://join.skype.com/invite/f5McdHuLGOab

**Pull request merged**
